filmapp/urls.py
from django.urls import path
from . import views
app_name='filmapp'

urlpatterns = [
    path('',views.index,name='index'),
    path('film/<int:film_id>/',views.detail,name='detail'),
    path('add/',views.add_film,name='add_film'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete'),

]

filmproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("filmapp.urls")),

]
if settings. DEBUG:
     urlpatterns += static(settings.STATIC_URL,
                           document_root=settings.STATIC_ROOT)
     urlpatterns += static(settings.MEDIA_URL,
                           document_root=settings.MEDIA_ROOT)

filmapp/models.py
from django.db import models

# Create your models here.
class Film(models.Model):
    name=models.CharField(max_length=250)
    img=models.ImageField(upload_to='pics')
    desc=models.TextField()
    year=models.IntegerField()


def __str__(self):
    return self.name

filmapp/forms.py
from django import forms
from .models import Film

class FilmForm(forms.ModelForm):
    class Meta:
        model=Film
        fields=['name','desc','year','img']

filmapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from . models import Film
from . forms import FilmForm

# Create your views here.
def index(request):
    film=Film.objects.all()
    context={
        'film_list':film
    }
    return render(request,"index.html",context)
def detail(request,film_id):
    film=Film.objects.get(id=film_id)
    return render(request,"detail.html",{'film':film})
def add_film(request):
     if request.method=="POST":
         name=request.POST.get('name',)
         desc=request.POST.get('desc',)
         year=request.POST.get('year',)
         img=request.FILES["img"]
         film=Film(name=name,desc=desc,year=year,img=img)
         film.save()
         return redirect('/')
     return render(request,"add.html")

def update(request,id):
    film=Film.objects.get(id=id)
    form=FilmForm(request.POST or None, request.FILES,instance=film)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'film':film})

def delete(request,id):
    if request.method=="POST":
        film=Film.objects.get(id=id)
        film.delete()
        return redirect('/')
    return render(request,'delete.html')

templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Enter Your Movie Name">
    <input type="text" name="desc" placeholder="Enter Movie Description">
    <input type="text" name="year" placeholder="Enter Year Of Movie">
    <input type="file" name="img">
    <input type="submit">

</form>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Film</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>

<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    ONLINE MOVIE STORE
  </a>
    <a href="{% url 'filmapp:add_film' %}" class="btn btn-primary">Add</a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

templates/delete.html
<form method="POST">
    {% csrf_token %}
    Are You Sure to delete this movie?
    <input type="Submit">
</form>

templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{film.img.url}}" width="300" height="400">
        </div>
        <div class="col-md-6">
            <h2>{{film.name}}</h2>
            <h4>{{film.desc}}</h4>
            <h6>{{film.year}}</h6>
            <a class="btn btn-warning" href="{% url 'filmapp:update' film.id %}">Update</a>
            <a class="btn btn-danger" href="{% url 'filmapp:delete' film.id %}">Delete</a>
        </div>
    </div>
</div>
{% endblock %}

templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="container-fluid mt-3">
    <div class="row mx-auto">
        {% for i in film_list %}
        <div class="col-md-3">
            <div class="card mx-auto mb-3" style="width: 18rem;">
            <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" height="350px">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.price}}</p>
    <a href="{% url 'filmapp:detail' i.id %}" class="btn btn-primary">View Details</a>
  </div>
</div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}